[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
time_locked = "5F3APs596H15YQeVXRfTYQwAGv2ynQCXJvDC9fc7LXUR"

[programs.localnet]
time_locked = "5F3APs596H15YQeVXRfTYQwAGv2ynQCXJvDC9fc7LXUR"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
